name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - "azure.yaml"
      - ".github/workflows/infra-deploy.yml"

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

# Set permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_ENV_NAME: ${{ github.event.inputs.environment || 'dev' }}
  AZURE_DEV_COLLECT_TELEMETRY: "no"

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Azure Developer CLI
        uses: Azure/setup-azd@v2

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Initialize azd environment
        run: |
          # Configure azd to use the OIDC credentials in GitHub Actions
          echo "Configuring azd authentication..."
          azd auth login --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }} --federated-credential-provider github

          echo "Setting up azd environment..."
          azd env new ${{ env.AZURE_ENV_NAME }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --location centralus || azd env select ${{ env.AZURE_ENV_NAME }}

      - name: Deploy infrastructure
        run: |
          azd provision --no-state

    #   - name: Deploy application
    #     run: |
    #       azd deploy
